package utils;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import dao.EmployeeDAO;
import models.Employee;
import models.PayrollRecord;

import java.io.FileOutputStream;

public class PayslipGenerator {

    public static String generate(PayrollRecord p) throws Exception {

        Employee emp = EmployeeDAO.getAll().stream().filter(e -> e.getEmpId() == p.getEmpId()).findFirst().orElse(null);
        if (emp == null) throw new Exception("Employee not found");

        String filename = "Payslip_" + emp.getName().replaceAll("\\s+","_") + "_" + p.getMonth() + "_" + p.getYear() + ".pdf";

        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(filename));
        document.open();

        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20);
        Paragraph title = new Paragraph("PaySyncX - Payslip", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        document.add(new Paragraph(" "));
        document.add(new Paragraph("Employee: " + emp.getName()));
        document.add(new Paragraph("Role: " + emp.getRole()));
        document.add(new Paragraph("Month/Year: " + p.getMonth() + "/" + p.getYear()));
        document.add(new Paragraph(" "));

        document.add(new Paragraph("Basic: ₹" + p.getBasic()));
        document.add(new Paragraph("Allowances: ₹" + p.getAllowances()));
        document.add(new Paragraph("Deductions: ₹" + p.getDeductions()));
        document.add(new Paragraph("Net Salary: ₹" + p.getNetSalary()));

        document.add(new Paragraph(" "));
        document.add(new Paragraph("Generated by PaySyncX"));
        document.add(new Paragraph("Date: " + new java.util.Date()));

        document.close();
        return filename;
    }
}
